In [1]:
from konlpy.tag import Okt
import pandas as pd
import numpy as np
import csv

In [2]:
global_csv = pd.read_csv('dataset/blog/global.csv', encoding="utf-8").append(pd.read_csv('dataset/news/global.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/global.csv', encoding="utf-8"))
active_csv = pd.read_csv('dataset/blog/active.csv', encoding="utf-8").append(pd.read_csv('dataset/news/active.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/active.csv', encoding="utf-8"))
challenge_csv = pd.read_csv('dataset/blog/challenge.csv', encoding="utf-8").append(pd.read_csv('dataset/news/challenge.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/challenge.csv', encoding="utf-8"))
sincerity_csv = pd.read_csv('dataset/blog/sincerity.csv', encoding="utf-8").append(pd.read_csv('dataset/news/sincerity.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/sincerity.csv', encoding="utf-8"))
communication_csv = pd.read_csv('dataset/blog/communication.csv', encoding="utf-8").append(pd.read_csv('dataset/news/communication.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/communication.csv', encoding="utf-8"))
patient_csv = pd.read_csv('dataset/blog/patient.csv', encoding="utf-8").append(pd.read_csv('dataset/news/patient.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/patient.csv', encoding="utf-8"))
honesty_csv = pd.read_csv('dataset/blog/honesty.csv', encoding="utf-8").append(pd.read_csv('dataset/news/honesty.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/honesty.csv', encoding="utf-8"))
responsibility_csv = pd.read_csv('dataset/blog/responsibility.csv', encoding="utf-8").append(pd.read_csv('dataset/news/responsibility.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/responsibility.csv', encoding="utf-8"))
creative_csv = pd.read_csv('dataset/blog/creative.csv', encoding="utf-8").append(pd.read_csv('dataset/news/creative.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/creative.csv', encoding="utf-8"))
teamwork_csv = pd.read_csv('dataset/blog/teamwork.csv', encoding="utf-8").append(pd.read_csv('dataset/news/teamwork.csv', encoding="utf-8")).append(pd.read_csv('dataset/keyword_daum/teamwork.csv', encoding="utf-8"))

In [3]:
def openStopword():
    f = open('dataset/stopwords/stopwords.csv', 'r', encoding='utf-8')
    reader = csv.reader(f)
    stopwords = list()

    for row in reader:
        stopwords.append(row[0])

    return stopwords

In [4]:
def tokenizer(raw, pos=["Noun","Verb"], stopword=openStopword()):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   # normalize 정제 과정
            stem=True    # stemming 정제 과정
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [5]:
okt = Okt()

keyword_names = ['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

In [6]:
all_data = global_csv.append(active_csv).append(challenge_csv).append(sincerity_csv).append(communication_csv)
all_data = all_data.append(patient_csv).append(honesty_csv).append(responsibility_csv).append(creative_csv).append(teamwork_csv)

In [7]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(all_data, test_size=0.33, random_state=42)

In [8]:
train.groupby("label").count()

sentence
label          
1          8103
2          7738
3          7450
4          6980
5          8535
6          8421
7          7905
8          8425
9          8345
10         8627

In [9]:
test.groupby("label").count()

sentence
label          
1          3944
2          3779
3          3707
4          3608
5          4280
6          4127
7          3929
8          4127
9          3958
10         4209

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(
    ngram_range=(1,3), #n-gram 3
    tokenizer=tokenizer,
    max_df=0.95,
    min_df=0,
    sublinear_tf=True
)

In [11]:
#tdm = vectorize.fit_transform(train["sentence"].values.astype('U'))
tdm = vectorize.fit_transform(train["sentence"].apply(lambda x: np.str_(x)))

In [12]:
vectorize.vocabulary_

{'내다': 199635,
 '사먹다': 516308,
 '편의점': 1110421,
 '심플': 646868,
 '리쿡': 343067,
 '상큼': 539235,
 '레몬': 333036,
 '크림': 1074018,
 '치킨': 1053535,
 '솔직': 590042,
 '후기': 1265291,
 '내다 사먹다': 200241,
 '사먹다 편의점': 516385,
 '편의점 심플': 1110475,
 '심플 리쿡': 646895,
 '리쿡 상큼': 343068,
 '상큼 레몬': 539244,
 '레몬 크림': 333081,
 '크림 치킨': 1074207,
 '치킨 솔직': 1053642,
 '솔직 후기': 591391,
 '내다 사먹다 편의점': 200258,
 '사먹다 편의점 심플': 516388,
 '편의점 심플 리쿡': 1110476,
 '심플 리쿡 상큼': 646896,
 '리쿡 상큼 레몬': 343069,
 '상큼 레몬 크림': 539246,
 '레몬 크림 치킨': 333083,
 '크림 치킨 솔직': 1074208,
 '치킨 솔직 후기': 1053644,
 '러시아어': 332263,
 '오늘': 730889,
 '외국어': 749259,
 '러시아어 오늘': 332351,
 '오늘 외국어': 732342,
 '러시아어 오늘 외국어': 332352,
 '인생': 841488,
 '준비': 955690,
 '학교': 1182992,
 '공부': 78937,
 '기질': 167129,
 '근성': 138359,
 '점수': 909150,
 '자다': 864246,
 '받다': 425658,
 '모든': 381779,
 '하다': 1135115,
 '착각': 1003333,
 '가지다': 13984,
 '들다': 312576,
 '끈기': 181689,
 '피나': 1129467,
 '노력': 209283,
 '알다': 673437,
 '핑계': 1133869,
 '쉬다': 607119,
 '포기': 1115084,
 '않다': 668882,

#### 기존 모델

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

In [14]:
text_clf_svm = Pipeline([('vect', vectorize),
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=1000, random_state=42))]) # 손실함수 기댓값 최소화

text_clf_svm = text_clf_svm.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

/home/.dlpc/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


#### Naive Bayes

In [15]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier

NB_pipeline = Pipeline([
                ('tfidf', vectorize),
                ('clf', OneVsRestClassifier(MultinomialNB(
                    fit_prior=True, class_prior=None))),
            ])

text_clf_nb = NB_pipeline.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

#### SVM - LinearSVC

In [16]:
from sklearn.svm import LinearSVC
SVC_pipeline = Pipeline([
                ('tfidf', vectorize),
                ('clf', OneVsRestClassifier(LinearSVC(), n_jobs=1)),
            ])

text_clf_svc = SVC_pipeline.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

#### Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
LogReg_pipeline = Pipeline([
                ('tfidf', vectorize),
                ('clf', OneVsRestClassifier(LogisticRegression(solver='sag'), n_jobs=1)),
            ])

text_clf_logreg = LogReg_pipeline.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

#### 예측점수 측정

In [19]:
# 기존 모델 svm
print("train", np.mean(text_clf_svm.predict(train["sentence"].apply(lambda x: np.str_(x))) == train["label"]))
print("test", np.mean(text_clf_svm.predict(test["sentence"].apply(lambda x: np.str_(x))) == test["label"]))

train 0.9845416506288879
test 0.9155007688623358


In [20]:
# Naive Bayes
print("train",np.mean(text_clf_nb.predict(train["sentence"].apply(lambda x: np.str_(x))) == train["label"]) )
print("test",np.mean(text_clf_nb.predict(test["sentence"].apply(lambda x: np.str_(x))) == test["label"]))

train 0.9836476737977874
test 0.8971993244094885


In [21]:
# SVM-LinearSVC
print("train",np.mean(text_clf_svc.predict(train["sentence"].apply(lambda x: np.str_(x))) == train["label"]))
print("test",np.mean(text_clf_svc.predict(test["sentence"].apply(lambda x: np.str_(x))) == test["label"]))

train 0.9958405244664076
test 0.9409866646499786


In [22]:
# Logistic Regression
print("train",np.mean(text_clf_logreg.predict(train["sentence"].apply(lambda x: np.str_(x))) == train["label"]) )
print("test",np.mean(text_clf_logreg.predict(test["sentence"].apply(lambda x: np.str_(x))) == test["label"]))

train 0.9788549646754988
test 0.9309032241800902


#### 기존 모델로 예측-----

In [23]:
text_clf_svm.predict(["능동적인 사람이 되자"])

array([2])

In [24]:
text_clf_svm.predict(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([ 1,  2,  3,  4,  5,  6,  6,  6,  9, 10])

In [25]:
text_clf_svm.predict(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([3])

In [26]:
text_clf_svm.decision_function(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([[-0.978674  , -0.99008353, -0.97014692, -0.99122914, -0.99902713,
        -0.9820617 , -1.0217902 , -1.00488911, -1.00514857, -1.01002735]])

#### 여러 모델 예측

In [27]:
def Predict(model,text):
    result = model.predict([text])
    print(keyword_names[result[0]-1])
    #return keyword_names[result[0]-1]

In [28]:
Predict(text_clf_svm, "개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")
Predict(text_clf_svm, "또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

능동
도전


In [29]:
Predict(text_clf_nb, "개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")
Predict(text_clf_nb, "또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

능동
도전


In [30]:
Predict(text_clf_svc, "개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")
Predict(text_clf_svc, "또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

능동
도전


In [31]:
Predict(text_clf_logreg, "개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")
Predict(text_clf_logreg, "또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

능동
도전


#### model dump

In [32]:
import pickle
import joblib
joblib.dump(text_clf_svm, 'SVM_190516.joblib')
joblib.dump(text_clf_nb, 'NB_190516.joblib')
joblib.dump(text_clf_svc, 'SVC_190516.joblib')
joblib.dump(text_clf_logreg, 'LogReg_190516.joblib')

['LogReg_190516.joblib']