In [1]:
from konlpy.tag import Okt
import pandas as pd
import numpy as np

In [2]:
global_csv = pd.read_csv('blog/global.csv', encoding="utf-8").append(pd.read_csv('news/global.csv', encoding="utf-8"))
active_csv = pd.read_csv('blog/active.csv', encoding="utf-8").append(pd.read_csv('news/active.csv', encoding="utf-8"))
challenge_csv = pd.read_csv('blog/challenge.csv', encoding="utf-8").append(pd.read_csv('news/challenge.csv', encoding="utf-8"))
sincerity_csv = pd.read_csv('blog/sincerity.csv', encoding="utf-8").append(pd.read_csv('news/sincerity.csv', encoding="utf-8"))
communication_csv = pd.read_csv('blog/communication.csv', encoding="utf-8").append(pd.read_csv('news/communication.csv', encoding="utf-8"))
patient_csv = pd.read_csv('blog/patient.csv', encoding="utf-8").append(pd.read_csv('news/patient.csv', encoding="utf-8"))
honesty_csv = pd.read_csv('blog/honesty.csv', encoding="utf-8").append(pd.read_csv('news/honesty.csv', encoding="utf-8"))
responsibility_csv = pd.read_csv('blog/responsibility.csv', encoding="utf-8").append(pd.read_csv('news/responsibility.csv', encoding="utf-8"))
creative_csv = pd.read_csv('blog/creative.csv', encoding="utf-8").append(pd.read_csv('news/creative.csv', encoding="utf-8"))
teamwork_csv = pd.read_csv('blog/teamwork.csv', encoding="utf-8").append(pd.read_csv('news/teamwork.csv', encoding="utf-8"))

In [3]:
import csv

pd.options.mode.chained_assignment = None
np.random.seed(0)

# Kolnpy
okt = Okt()

rawdata = [
    global_csv,
    active_csv,
    challenge_csv,
    sincerity_csv,
    communication_csv,
    patient_csv,
    honesty_csv,
    responsibility_csv,
    creative_csv,
    teamwork_csv
]

keyword_names = ['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

# 불용어리스트 불러오는 과정
f = open('dataset/stopwords/stopwords.csv', 'r', encoding='utf-8')
reader = csv.reader(f)
stopwords = list()

for row in reader:
    stopwords.append(row[0])

In [4]:
# raw한 문장데이터를 분석에 알맞게 정제하도록 한다.
def tokenizer(raw, pos=["Noun","Verb"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   # normalize 정제 과정
            stem=True    # stemming 정제 과정
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [5]:
global_csv.head()

label                                           sentence
0      1                          업무상횡령 외국에서는 어떻게 대처해야 할까요?
1      1  업무상횡령 외국에서는 어떻게 대처해야 할까요? 안녕하세요. 성큼 다가온 5월! 다채...
2      1                               압구정 로데오 맛집 외국같은 느낌~!
3      1  다행히 친구 중에 영어를 엄청 잘하는 친구가 있어서 해석 좀 해보라고 했더니 읽어보...
4      1                                   외국영어캠프 경험해야 알아요!

In [6]:
global_csv["sentence"]

0                             업무상횡령 외국에서는 어떻게 대처해야 할까요?
1     업무상횡령 외국에서는 어떻게 대처해야 할까요? 안녕하세요. 성큼 다가온 5월! 다채...
2                                  압구정 로데오 맛집 외국같은 느낌~!
3     다행히 친구 중에 영어를 엄청 잘하는 친구가 있어서 해석 좀 해보라고 했더니 읽어보...
4                                      외국영어캠프 경험해야 알아요!
5     마주치는 외국인 분에게 인사를 먼저 하더라고요 얘가 이 정도로 자신감이 많은 애였나...
6                                              이태원 외국서점
7     그런데 비영어권 언어는 구하기가 힘들어 여기저기 알아보다가 지인찬스로 알게 된 곳이...
8                                      외국동화 생각하는 힘을 키워요
9     생각하는 힘을 키우기에도 좋은 외국동화 논리꼬마철학동화에요. 철학동화라고하면 좀 지...
10                  외국항공사 승무원 채용 2019년 최근 합격후기 5월이후채용은?
11    외국항공사 승무원 채용 2019년 최근 합격후기 5월이후채용은? 안녕하세요~ 날씨가...
12           파주 핫플레이스 카페 [더티트렁크]추천 세상에 여기가 우리나라야? 외국온줄!
13    직원분들이 열심히 만들고 계셨어요 전 여기를 보고 정말 외국에 온거 같다 기분을 느...
0                         중국 미국 관세 위협에 "외국 압력에 굴복 않을 것"
1     중국 외교부가 미국의 새로운 관세 위협 속에 "중국은 외국의 압력에 굴복하지 않을 ...
2                   '출국은 안하고 면세 화장품만 사모아?' 수상한 외국인 추적조사
3     모으는 외국인은 관세청이 추적조사하고 1년간 제품 구입을 막는 방안이 추진된

In [7]:
all_data = global_csv.append(active_csv).append(challenge_csv).append(sincerity_csv).append(communication_csv)
all_data = all_data.append(patient_csv).append(honesty_csv).append(responsibility_csv).append(creative_csv).append(teamwork_csv)

In [8]:
all_data

label                                           sentence
0       1                          업무상횡령 외국에서는 어떻게 대처해야 할까요?
1       1  업무상횡령 외국에서는 어떻게 대처해야 할까요? 안녕하세요. 성큼 다가온 5월! 다채...
2       1                               압구정 로데오 맛집 외국같은 느낌~!
3       1  다행히 친구 중에 영어를 엄청 잘하는 친구가 있어서 해석 좀 해보라고 했더니 읽어보...
4       1                                   외국영어캠프 경험해야 알아요!
5       1  마주치는 외국인 분에게 인사를 먼저 하더라고요 얘가 이 정도로 자신감이 많은 애였나...
6       1                                           이태원 외국서점
7       1  그런데 비영어권 언어는 구하기가 힘들어 여기저기 알아보다가 지인찬스로 알게 된 곳이...
8       1                                   외국동화 생각하는 힘을 키워요
9       1  생각하는 힘을 키우기에도 좋은 외국동화 논리꼬마철학동화에요. 철학동화라고하면 좀 지...
10      1                외국항공사 승무원 채용 2019년 최근 합격후기 5월이후채용은?
11      1  외국항공사 승무원 채용 2019년 최근 합격후기 5월이후채용은? 안녕하세요~ 날씨가...
12      1         파주 핫플레이스 카페 [더티트렁크]추천 세상에 여기가 우리나라야? 외국온줄!
13      1  직원분들이 열심히 만들고 계셨어요 전 여기를 보고 정말 외국에 온거 같다 기분을 느...
0       1                      중국 미국 관세 위협에 "외국 압력에 굴복 않을 것"
1       1  중국 외교부가 미국의 새로운 관세 위협 속에 "중국은 외국의 압력에 굴복하지 않을 ...
2       1                '출국은 안하고 면세 화장품만 사모아?' 수상한 외국인 추적조사
3       1  모으는 외국인은 관세청이 추적조사하고 1년간 제품 구입을 막는 방안이 추진된다. 1...
4       1                         외국인 3월 韓상장주식·채권 3.1조원어치 샀다
5       1  지난달 외국인들의 국내 상장주식·채권투자가 늘어난 것으로 나타났다. 금융감독원이 1...
6       1                       부산대 동문교수회 외국인 유학생 '점심 나눔' 행사
7       1  중인 외국인 유학생을 대상으로 개교기념일(5월 15일)이 포함된 주인 지난 13일부...
8       1                             마산중부서 외국인 대상 문화 존중 캠페인
9       1  마산중부경찰서(서장 김균)는 체류 외국인들의 문화를 존중하는 의미에서 창원노동자지원...
10      1                     주한외국무관단 DMZ 평화의 길 '금강산 전망대' 방문
11      1  주한외국무관단이 강원도와 경기도 일대 안보현장을 견학하고 남북 군사분야 합의에 따른...
12      1                   원화가치 급속 추락…외국인자금 대량이탈시 '증시패닉' 우려
13      1  증시에서는 환율 상승으로 인해 외국인 자금 이탈이 심해지면서 환율은 더욱 오르고 주...
14      1                   한국MSD 외국인 임원 왜 이러나?…이번엔 '성추행' 논란
15      1  한국MSD의 외국인 임원이 또 다시 한국인 임직원에게 횡포를 저지른 것이 알려져 논...
..    ...                                                ...
10     10                     호남새마을금고 사라신용협동조합 디자인플레이 창립 기념일
11     10  15일 호남새마을금고 사라신용협동조합 디자인플레이 등이 창립기념일을 맞아 양질의 고...
12     10                                 중국 첫 5G안전협동혁신센터 설립
13     10  협동혁신센터가 최근 성두(成都)에 설립되었다. 해당 센터 AsiaInfo와 중국정보...
14     10                       레미콘협동조합 등 7개 단체 '콘크리트의 날' 제정
15     10  한국레미콘공업협동조합연합회(회장 배조웅)는 지난 9일 제주 신화월드 랜딩컨벤션센터에...
16     10                     AI로 무장한 작업 동료…'협동로봇'이 제조혁신 이끈다
17     10  수작업으로 하던 부품 용접을 ‘협동로봇’에 맡겼다. 기존 5~7분가량 걸리던 공정시...
18     10  [최양부칼럼-협동조합은 바른마음이다.](1부 왜 협동조합인가?) - 4회 선진국의 ...
19     10  최양부 바른협동조합실천운동본부 이사장 [한국농어촌방송=최양부 바른협동조합실천운동본부...
20     10                     AI로 무장한 작업 동료…'협동로봇'이 제조혁신 이끈다
21     10  수작업으로 하던 부품 용접을 ‘협동로봇’에 맡겼다. 기존 5~7분가량 걸리던 공정시...
22     10  [최양부칼럼-협동조합은 바른마음이다.](1부 왜 협동조합인가?) - 4회 선진국의 ...
23     10  최양부 바른협동조합실천운동본부 이사장 [한국농어촌방송=최양부 바른협동조합실천운동본부...
24     10                            NH농협 도농협동범국민운동...위촉식 개최
25     10  농협제주지역본부(본부장 변대근)와 김녕농협(조합장 오충규)은 지난 12일 제주종합경...
26     10                          제주중앙신용협동조합 "지역 경제 발전에 기여"
27     10  18일 창립 56주년을 맞는 제주중앙신용협동조합(이사장 김태용·사진)은 '조합원 감...
28     10                           경기인천기계공업협동조합-市지방행정동우회 협약
29     10  경기인천기계공업협동조합은 지난 10일 ㈔인천시지방행정동우회와 업무협약을 체결했다. ...
30     10                   인천 미추홀구 미래사회협동조합 보육교사 위한 전문서적 출판
31     10  미래사회건강교육 협동조합이 펴낸 '행동수정 심리 솔루션 12가지'. 사진=미추홀구 ...
32     10                 【서천】장항고 마을교육공동체 사회적 협동조합 ‘장보고’ 오픈식
33     10   장항고등학교(교장 최동우)는 지난 10일 마을 교육공동체 사회적 협동조합 ‘장보고...
34     10                                  인천기계협동조합·행정동우회 협약
35     10  ▲ 인천일보 INCHEONILBO 경기인천기계협동조합(조합장 장규진)과 인천광역시 ...
36     10                          부민하늘농원협동조합 제철 채소 나눔 행사 개최
37     10  부산 서구(구청장 공한수) 부민하늘농원협동조합(이사장 구자홍)은 지난 10일 가정의...
38     10            도전과 협동으로 하나 되는 플러스원 익사이팅 '어빌리티 핸드 업 미션'
39     10  첫 번째로 다양한 팀빌딩 프로그램과 게임을 통해 프로그램에 참여한 직장인들에게 업무...

[540 rows x 2 columns]

In [9]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(all_data, test_size=0.33, random_state=42)
train["label"] = pd.Categorical(train["label"])

In [10]:
train.groupby("label").count()

sentence
label          
1            34
2            30
3            40
4            37
5            40
6            37
7            34
8            39
9            36
10           34

In [11]:
test.groupby("label").count()

sentence
label          
1            20
2            24
3            14
4            17
5            14
6            17
7            20
8            15
9            18
10           20

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(
    ngram_range=(1,2),
    tokenizer=tokenizer,
    max_df=0.95,
    min_df=0,
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)

In [13]:
from datetime import datetime
now = datetime.now()
tdm = vectorize.fit_transform(train["sentence"].values.astype('U'))
after = datetime.now()
after-now

datetime.timedelta(seconds=5, microseconds=514252)

In [14]:
#tdm = vectorize.fit_transform(train["sentence"].values.astype('U'))
from datetime import datetime
now = datetime.now()
tdm = vectorize.fit_transform(train["sentence"].apply(lambda x: np.str_(x)))
after = datetime.now()
after-now

datetime.timedelta(seconds=2, microseconds=116340)

In [15]:
vectorize.vocabulary_

{'하동군': 6691,
 '지역': 5537,
 '청소년': 5748,
 '지난': 5492,
 '자매도시': 4890,
 '안양시': 3737,
 '찾다': 5705,
 '현지': 6972,
 '교류': 602,
 '행사': 6913,
 '가지다': 90,
 '밝히다': 2477,
 '활동': 7111,
 '도시': 1600,
 '농어촌': 1254,
 '상호': 3053,
 '방문': 2494,
 '통해': 6204,
 '서로': 3095,
 '하동군 지역': 6693,
 '지역 청소년': 5545,
 '청소년 지난': 5754,
 '지난 자매도시': 5504,
 '자매도시 안양시': 4891,
 '안양시 찾다': 3738,
 '찾다 현지': 5709,
 '현지 청소년': 6973,
 '청소년 교류': 5750,
 '교류 행사': 625,
 '행사 가지다': 6914,
 '가지다 밝히다': 94,
 '밝히다 지역': 2491,
 '교류 활동': 632,
 '활동 도시': 7112,
 '도시 농어촌': 1602,
 '농어촌 청소년': 1257,
 '청소년 상호': 5753,
 '상호 방문': 3054,
 '방문 통해': 2502,
 '통해 서로': 6207,
 '열정': 4035,
 '근성': 805,
 '전문성': 5081,
 '겸손': 329,
 '대해': 1521,
 '강의': 170,
 '하다': 6455,
 '음악': 4500,
 '고전': 436,
 '이야기': 4596,
 '세다': 3216,
 '냉전': 1195,
 '말기': 2046,
 '핵겨울': 6900,
 '갖다': 183,
 '업무': 3867,
 '농협': 1264,
 '금융': 850,
 '주역': 5367,
 '기르다': 915,
 '바라다': 2381,
 '당부': 1405,
 '한편': 6829,
 '열정 근성': 4036,
 '근성 전문성': 825,
 '전문성 겸손': 5083,
 '겸손 대해': 330,
 '대해 강의': 1522,
 '강의 하다': 174,
 '하다 

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

In [17]:
text_clf_svm = Pipeline([('vect', vectorize),
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=1000, random_state=42))]) # 손실함수 기댓값 최소화

text_clf_svm = text_clf_svm.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

C:\Users\abcd_\Anaconda3\envs\section2\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [18]:
predicted_svm = text_clf_svm.predict(train["sentence"])#학습데이터 테스트
np.mean(predicted_svm == train["label"])

1.0

In [19]:
predicted_svm = text_clf_svm.predict(test["sentence"])#테스트데이터
np.mean(predicted_svm == test["label"])

0.9162011173184358

In [20]:
text_clf_svm.predict(["능동적인 사람이 되자"])

array([8], dtype=int64)

In [21]:
text_clf_svm.predict(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([ 8,  8, 10,  4,  4,  4,  4,  6,  8,  4], dtype=int64)

In [22]:
text_clf_svm.decision_function(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([[-0.85475942, -0.89347097, -0.86250482, -0.83972169, -0.76736483,
        -0.83548355, -0.89353435, -0.32964253, -0.85862927, -0.91023379],
       [-0.81913036, -0.87290687, -0.79960641, -0.8151381 , -0.84902673,
        -0.79516591, -0.85381286, -0.61096913, -0.79867797, -0.838707  ],
       [-0.8676709 , -0.61561281, -0.852972  , -0.84791671, -0.88300042,
        -0.86963604, -0.9001136 , -0.87987482, -0.86447476, -0.46172338],
       [-0.81102968, -0.83288001, -0.78388157, -0.77272869, -0.82186565,
        -0.78468269, -0.84332964, -0.80586181, -0.7767585 , -0.82345867],
       [-0.81102968, -0.83288001, -0.78388157, -0.77272869, -0.82186565,
        -0.78468269, -0.84332964, -0.80586181, -0.7767585 , -0.82345867],
       [-0.81102968, -0.83288001, -0.78388157, -0.77272869, -0.82186565,
        -0.78468269, -0.84332964, -0.80586181, -0.7767585 , -0.82345867],
       [-0.81102968, -0.83288001, -0.78388157, -0.77272869, -0.82186565,
        -0.78468269, -0.84332964, -0.80586181

In [23]:
text_clf_svm.predict(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([8], dtype=int64)

In [24]:
text_clf_svm.decision_function(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([[-0.88944851, -0.57132785, -1.03158577, -0.86080385, -0.79339292,
        -0.66009636, -0.96188055, -0.43605995, -0.96549553, -0.81274776]])

In [25]:
text_clf_svm.predict(["능동적인 사람이 되자"])[0]

8

In [26]:
text_clf_svm.decision_function(["능동적인 사람이 되자"])

array([[-0.84323779, -0.90073531, -0.81103153, -0.83569175, -0.87602994,
        -0.77984498, -0.82818363, -0.49993139, -0.81087207, -0.85697096]])

In [27]:
keyword_names

['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

In [28]:
def SVMpredict(text):
    result = text_clf_svm.predict([text])
    return keyword_names[result[0]-1]

In [29]:
SVMpredict("개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")

'능동'

In [30]:
SVMpredict("또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

'팀워크'

In [31]:
import pickle
from sklearn.externals import joblib

In [32]:
saved_model = pickle.dumps(text_clf_svm)

In [33]:
joblib.dump(text_clf_svm, 'SVMmodel.pkl') 

['SVMmodel.pkl']

In [34]:
clf_from_joblib = joblib.load('filename.pkl') 
clf_from_joblib.predict(["또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다."])

array([10], dtype=int64)

In [35]:
filename = 'SVMmodel.pkl'
clf_from_pickle = joblib.load(filename)

In [36]:
clf_from_pickle.predict(["또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다."])

array([10], dtype=int64)

In [37]:
clf_from_pickle.predict(["오늘도 캡스톤을 하러 학교에 남았다"])

array([2], dtype=int64)