In [1]:
from konlpy.tag import Okt
import pandas as pd
import numpy as np

In [2]:
#파일 큰 버전
global_csv = pd.read_csv('dataset/blog/global.csv', encoding="utf-8").append(pd.read_csv('dataset/news/global.csv', encoding="utf-8"))
active_csv = pd.read_csv('dataset/blog/active.csv', encoding="utf-8").append(pd.read_csv('dataset/news/active.csv', encoding="utf-8"))
challenge_csv = pd.read_csv('dataset/blog/challenge.csv', encoding="utf-8").append(pd.read_csv('dataset/news/challenge.csv', encoding="utf-8"))
sincerity_csv = pd.read_csv('dataset/blog/sincerity.csv', encoding="utf-8").append(pd.read_csv('dataset/news/sincerity.csv', encoding="utf-8"))
communication_csv = pd.read_csv('dataset/blog/communication.csv', encoding="utf-8").append(pd.read_csv('dataset/news/communication.csv', encoding="utf-8"))
patient_csv = pd.read_csv('dataset/blog/patient.csv', encoding="utf-8").append(pd.read_csv('dataset/news/patient.csv', encoding="utf-8"))
honesty_csv = pd.read_csv('dataset/blog/honesty.csv', encoding="utf-8").append(pd.read_csv('dataset/news/honesty.csv', encoding="utf-8"))
responsibility_csv = pd.read_csv('dataset/blog/responsibility.csv', encoding="utf-8").append(pd.read_csv('dataset/news/responsibility.csv', encoding="utf-8"))
creative_csv = pd.read_csv('dataset/blog/creative.csv', encoding="utf-8").append(pd.read_csv('dataset/news/creative.csv', encoding="utf-8"))
teamwork_csv = pd.read_csv('dataset/blog/teamwork.csv', encoding="utf-8").append(pd.read_csv('dataset/news/teamwork.csv', encoding="utf-8"))

In [3]:
import csv

pd.options.mode.chained_assignment = None
np.random.seed(0)

# Kolnpy
okt = Okt()

rawdata = [
    global_csv,
    active_csv,
    challenge_csv,
    sincerity_csv,
    communication_csv,
    patient_csv,
    honesty_csv,
    responsibility_csv,
    creative_csv,
    teamwork_csv
]

keyword_names = ['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

# 불용어리스트 불러오는 과정
f = open('dataset/stopwords/stopwords.csv', 'r', encoding='utf-8')
reader = csv.reader(f)
stopwords = list()

for row in reader:
    stopwords.append(row[0])

In [4]:
# raw한 문장데이터를 분석에 알맞게 정제하도록 한다.
def tokenizer(raw, pos=["Noun","Verb"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   # normalize 정제 과정
            stem=True    # stemming 정제 과정
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [5]:
global_csv.head()

label                                           sentence
0      1                 외국어로 먹고 살기-3) 대 프로젝트를 위한 소 프로젝트 실시
1      1  외국어로 먹고 사는 것에 대해 진지하게 생각해봤을 때 내가 고려해야 할 테마는 두가...
2      1                                 해외마케팅-외국어 홈페이지 만들기
3      1  해외마케팅의 한 부분으로 외국어 홈페이지 만들기를 해온지 수개월 되었다. 중간중간 ...
4      1                     내가 생각하는 효과적인 외국어 회화 공부방법(주절주절)

In [6]:
global_csv["sentence"]

0                      외국어로 먹고 살기-3) 대 프로젝트를 위한 소 프로젝트 실시
1       외국어로 먹고 사는 것에 대해 진지하게 생각해봤을 때 내가 고려해야 할 테마는 두가...
2                                      해외마케팅-외국어 홈페이지 만들기
3       해외마케팅의 한 부분으로 외국어 홈페이지 만들기를 해온지 수개월 되었다. 중간중간 ...
4                          내가 생각하는 효과적인 외국어 회화 공부방법(주절주절)
5       내가 생각하는 효과적인 외국어 회화 공부방법(주절주절) 오늘은 여러분께 도움이 됬으...
6                                   2019 북경외국어대학교 교사연수 후기
7       올 초에는 국제중국어교육학과의 네분의 선생님께서 북경외국어대학에서 진행한 교사연수에...
8                         혼자베트남어공부 하고싶으시다면 외국어독학은 랭쿡 에서!!
9       여행을 위해 간단한 베트남어를 공부하고싶어 시작한 외국어독학 어학사이트 랭쿡 ! 혼...
10                        학점은행제 외국어로서의한국어학 한국어교원2급자격증취득방법
11      # 한국어교원2급자격증 이어서 2급의 자격증은 취득을 위해선2가지의 선택지가 있어요...
12                                 대구외국어학원 욕심있다면 이렇게 해봐요!
13      또한 대구외국어학원은 토익도 하고 있습니다. 토익은 문법 기초토익 오백오십 플러스 ...
14                             [INTERVIEW] 실용외국어학과 우소아 학우
15      오늘은 실용외국어학과에서 영어와 중국어를 전공하고 최근 신라면세점에서 근무를 시작하...
16               자영업과 사업의 차이(부제 : 외국어 공부 힘들때 이렇게도 생각해 보자)
17      외국어 공부

In [7]:
all_data = global_csv.append(active_csv).append(challenge_csv).append(sincerity_csv).append(communication_csv)
all_data = all_data.append(patient_csv).append(honesty_csv).append(responsibility_csv).append(creative_csv).append(teamwork_csv)

In [8]:
all_data

label                                           sentence
0         1                 외국어로 먹고 살기-3) 대 프로젝트를 위한 소 프로젝트 실시
1         1  외국어로 먹고 사는 것에 대해 진지하게 생각해봤을 때 내가 고려해야 할 테마는 두가...
2         1                                 해외마케팅-외국어 홈페이지 만들기
3         1  해외마케팅의 한 부분으로 외국어 홈페이지 만들기를 해온지 수개월 되었다. 중간중간 ...
4         1                     내가 생각하는 효과적인 외국어 회화 공부방법(주절주절)
5         1  내가 생각하는 효과적인 외국어 회화 공부방법(주절주절) 오늘은 여러분께 도움이 됬으...
6         1                              2019 북경외국어대학교 교사연수 후기
7         1  올 초에는 국제중국어교육학과의 네분의 선생님께서 북경외국어대학에서 진행한 교사연수에...
8         1                    혼자베트남어공부 하고싶으시다면 외국어독학은 랭쿡 에서!!
9         1  여행을 위해 간단한 베트남어를 공부하고싶어 시작한 외국어독학 어학사이트 랭쿡 ! 혼...
10        1                    학점은행제 외국어로서의한국어학 한국어교원2급자격증취득방법
11        1  # 한국어교원2급자격증 이어서 2급의 자격증은 취득을 위해선2가지의 선택지가 있어요...
12        1                             대구외국어학원 욕심있다면 이렇게 해봐요!
13        1  또한 대구외국어학원은 토익도 하고 있습니다. 토익은 문법 기초토익 오백오십 플러스 ...
14        1                         [INTERVIEW] 실용외국어학과 우소아 학우
15        1  오늘은 실용외국어학과에서 영어와 중국어를 전공하고 최근 신라면세점에서 근무를 시작하...
16        1           자영업과 사업의 차이(부제 : 외국어 공부 힘들때 이렇게도 생각해 보자)
17        1  외국어 공부를 예로 들어보겠다. *네이티브 중국어 때문에 중국어 공부 관련 상담도 ...
18        1                           원투무에타이 킥복싱 관장의 외국어 공부법#1
19        1  뜬금없이 의정부에서 무에타이 킥복싱 체육관을 운영하는 관장이라는 직업의 사람이 외국...
20        1                              외국어회화 사이트 랭쿡 육아맘 수강후기
21        1  #외국어독학사이트추천 영어공부에 대한 열망은 대단하지만 아이 키우는 엄마가 어딜 가...
22        1                       39. 외국어 할 때 만나는 또 다른 내가 궁금하다
23        1  친구와 다녀온 일본 여행을 통해 외국어를 말하고 있는 또다른 자신의 모습을 발견하고...
24        1                         현존하는 외국어 학습 방법중 가장 효율적인 방법
25        1  "Reading without a pencil is just daydreaming"...
26        1              대전 유성구 소식 충남대학교 국제언어교육원에서 외국어 특강 신청해요
27        1  충남대학교 국제언어교육원에서 외국어 특강 신청해요 충남대학교 국제언어교육원을 알고 ...
28        1                  인천 원어민 영어프리토킹 전화회화 자신감충전 외국어 완전정복
29        1  이제는 국제화 시대에 발맞추어 기본 외국어 1개정도는 학습해야만 할것입니다. 요즘에...
...     ...                                                ...
5990     10               착한보청기협동조합 전국센터 유명브랜드 보청기 봄맞이 특가행사 실시
5991     10  국내 최초 정부가 인정하고 지원하는 착한보청기협동조합이 ‘봄맞이 보청기 특가 행사’...
5992     10     [잘가 여행지-봄]펭귄마을 발을 딛는 순간 1970∼80년대로 돌아가는 추억 놀이터
5993     10  com 펭귄마을 입구[사진=양림동 남구관광사업단협동조합 대표 김수삼 제공] 서울에 ...
5994     10                      두산로보틱스 中 협동로봇 시장 첫발…판매망 확보 박차
5995     10  두산로보틱스 협동로봇 공급을 위한 대리점 계약을 체결했다고 19일 밝혔다. 이날 계...
5996     10                   [종합] 제주특별자치도 군장병의 선택으로 새로운 판로 확보
5997     10  연석회의에서는 가공 총괄수협(한림수산업협동조합)을 정하고 가공 물량의 안정적 확보를...
5998     10                           남해군 경제살리기위원회， 신임위원 3명 위촉
5999     10  송홍주 남해신용협동조합장이 경제살리기위원회의 신임위원으로 위촉됐다고 밝혔다. 남해군...
6000     10                   [종합] 제주특별자치도 군장병의 선택으로 새로운 판로 확보
6001     10  연석회의에서는 가공 총괄수협(한림수산업협동조합)을 정하고 가공 물량의 안정적 확보를...
6002     10                           남해군 경제살리기위원회， 신임위원 3명 위촉
6003     10  송홍주 남해신용협동조합장이 경제살리기위원회의 신임위원으로 위촉됐다고 밝혔다. 남해군...
6004     10                  [선샤인 CEO] 임준택 수협중앙회장 '든든한 리더십' 선봬
6005     10  임 회장은 지난 선거 당시 어민·조합·중앙회가 모두 잘 살 수 있는 환경을 만들기 ...
6006     10                         전자산업협동조합 23대 이사장에 정명화씨 재선임
6007     10  한국전자산업협동조합은 14일 제52회 정기총회에서현 이사장인 (주)텔코전자 정명화 ...
6008     10                         경북도의회  문화관광 활성화는 곧 일자리 창출 
6009     10  종합토론에서 김상헌 의원(포항)은  협동조합이 가질 수 있는 단점을 극복하고 순기능...
6010     10        국민대-서울역수제화사회적협동조합 도시재생 활성화 및 산학협력 위한 MOU 체결
6011     10  협동조합(이사장 박해권)은 지난 30일 서울역 일대 문화적 도시재생 활성화 및 산학...
6012     10                   제3차 지속가능한 농업개발을 위한 글로벌 ODA 포럼 개최
6013     10  농식품부는 농업분야 ODA 사업을 추진해오고 있으며 2017년에는 '국제농업개발사업...
6014     10       성.미가엘종합사회복지관-사회적협동조합M커뮤니티 '우리동네 골목길 놀이터' MOU
6015     10  사회적협동조합M커뮤니티(대표이사 이명선)와 ‘우리동네 골목길 놀이터’를 원활하게 추...
6016     10                           전남농협 ‘상호금융 사업추진 전략회의’ 개최
6017     10  감동을 주는 100년 전남 상호금융” 구현에 앞장설 것을 다짐하며 ‘농심을 가슴에 ...
6018     10           학부모 이끌고 경기도교육청 밀고… 국내 첫 '협동조합 유치원' 설립 탄력
6019     10  학부모들이 직접 유치원을 설립해 투명성과 공공성을 회복하자며 추진했던 협동조합 유치...

[98073 rows x 2 columns]

In [9]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(all_data, test_size=0.33, random_state=42)
train["label"] = pd.Categorical(train["label"])

In [10]:
train.groupby("label").count()

sentence
label          
1          6375
2          6264
3          5838
4          6731
5          6719
6          6831
7          6786
8          6757
9          6498
10         6901

In [11]:
test.groupby("label").count()

sentence
label          
1          3116
2          3002
3          2842
4          3402
5          3388
6          3347
7          3377
8          3449
9          3151
10         3288

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(
    ngram_range=(1,2),
    tokenizer=tokenizer,
    max_df=0.95,
    min_df=0,
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)

In [13]:
#tdm = vectorize.fit_transform(train["sentence"].values.astype('U'))
from datetime import datetime
now = datetime.now()
tdm = vectorize.fit_transform(train["sentence"].apply(lambda x: np.str_(x)))
after = datetime.now()
after-now

datetime.timedelta(seconds=371, microseconds=102505)

In [14]:
vectorize.vocabulary_

{'로마': 132317,
 '아카데미': 266793,
 '부문': 193986,
 '후보': 500891,
 '버닝': 179613,
 '최종': 416221,
 '탈락': 434334,
 '로마 아카데미': 132338,
 '아카데미 부문': 266840,
 '부문 후보': 194125,
 '후보 버닝': 500939,
 '버닝 최종': 179663,
 '최종 후보': 416293,
 '후보 탈락': 500997,
 '배심원': 177625,
 '문소리': 158611,
 '원칙': 313195,
 '사랑': 206874,
 '폭풍': 451423,
 '애교': 273379,
 '배심원 문소리': 177633,
 '문소리 원칙': 158621,
 '원칙 사랑': 313237,
 '사랑 폭풍': 207134,
 '폭풍 애교': 451439,
 '성가': 226920,
 '서다': 220278,
 '번쩍': 180880,
 '성가 서다': 226950,
 '서다 번쩍': 220396,
 '번쩍 번쩍': 180883,
 '봉환': 192740,
 '상공': 214747,
 '시장': 252198,
 '진흥': 399530,
 '공단': 30721,
 '이사장': 330293,
 '서울': 221753,
 '성동구': 227806,
 '위치': 315291,
 '디지털': 125307,
 '인쇄': 339588,
 '협동조합': 487030,
 '찾다': 405729,
 '설립': 226123,
 '되다': 115323,
 '정주환': 370847,
 '설비': 226548,
 '온라인': 299689,
 '주문': 382113,
 '시스템': 251365,
 '구축': 45724,
 '하다': 458234,
 '봉환 상공': 192741,
 '상공 시장': 214768,
 '시장 진흥': 252545,
 '진흥 공단': 399539,
 '공단 이사장': 30802,
 '이사장 서울': 330461,
 '서울 성동구': 221977,
 '성동구 위치': 2278

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

In [16]:
text_clf_svm = Pipeline([('vect', vectorize),
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, max_iter=1000, random_state=42))]) # 손실함수 기댓값 최소화

text_clf_svm = text_clf_svm.fit(train["sentence"].apply(lambda x: np.str_(x)), train["label"])

C:\Users\abcd_\Anaconda3\envs\section2\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


In [18]:
predicted_svm = text_clf_svm.predict(train["sentence"].apply(lambda x: np.str_(x)))#학습데이터 테스트
np.mean(predicted_svm == train["label"])

0.977034759846594

In [19]:
predicted_svm = text_clf_svm.predict(test["sentence"].apply(lambda x: np.str_(x)))#테스트데이터
np.mean(predicted_svm == test["label"])

0.9135794840105051

In [20]:
text_clf_svm.predict(["능동적인 사람이 되자"])

array([2], dtype=int64)

In [21]:
text_clf_svm.predict(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([ 1,  2,  3, 10,  2,  6,  6,  6,  8,  8], dtype=int64)

In [22]:
text_clf_svm.decision_function(["글로벌역량","능동","도전","성실","소통","인내심","정직","주인의식","창의","팀워크"])

array([[-0.96409606, -0.99997964, -1.00332412, -0.9968046 , -0.97943058,
        -0.99692807, -1.00257339, -0.96903637, -0.98636475, -1.00443723],
       [-1.0089106 , -0.95816133, -0.99985091, -0.99153512, -0.99971445,
        -0.99698269, -0.99902481, -0.96129025, -0.99791204, -1.00830927],
       [-1.00463468, -1.00097837, -0.90848538, -1.00842698, -1.02492255,
        -0.98568577, -1.00940821, -0.98079621, -1.01776887, -1.02193362],
       [-1.00206865, -0.99578037, -0.99590421, -0.99389808, -0.99751685,
        -0.98233169, -0.99336753, -0.99549919, -0.99565325, -0.98054933],
       [-0.99889181, -0.97089509, -1.00536359, -0.98967307, -0.99082953,
        -1.00073238, -0.98476675, -0.98989165, -1.00666457, -1.0267867 ],
       [-0.99936554, -0.99507457, -0.99475801, -0.9920105 , -0.99851561,
        -0.98530227, -0.99833914, -0.99172938, -0.99633738, -0.99529465],
       [-0.99852711, -0.99552453, -0.99077997, -0.99051673, -0.99573697,
        -0.98097714, -0.99061944, -1.00715362

In [23]:
text_clf_svm.predict(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([4], dtype=int64)

In [24]:
text_clf_svm.decision_function(["[열정을 갖고 끊임없이 노력하는 사람] 우선 주어진 일에 실패를 두려워하지 않고 끊임없이 도전하는 것입니다. 노력은 배신하지 않는다고 생각합니다. 주어진 일에 관한 분야의 역량을 함양하고자 시간 투자를 계속해서 쏟으며, 그 일을 반복하여 제 것으로 만듭니다. 저는 지금도 현재 진행형이며, 미래에도 멈추지 않고 달려 나가는 인재가 되고 싶습니다. 항상 배우고자 하고, 저 자신에게 나태해지지 않는 마음가짐으로 모든 일을 대할 것입니다. 팀 내부에서 저의 역할이 무엇인지 먼저 이해하고 팀원 간의 협력을 가장 중요시 여길 것입니다. 팀 프로젝트를 진행 할 때 가장 중요한 것은 팀원 간의 조화라고 생각하기 때문입니다. 이를 통해 어제보다 오늘의 제가, 오늘보다 내일의 제가 더 나은 사람이길 바랍니다. 안주하는 삶에 만족하지 않고 저의 가능성을 최대로 발휘하고 싶습니다. CJ올리브네트웍스에서도 발전하는 IT서비스와 시스템을 개발, 운영하기 위해 항상 새로운 도전에 주저없이 뛰어들겠습니다."])

array([[-0.98651706, -0.99569828, -0.983264  , -0.97364758, -0.98027515,
        -0.98338284, -1.02620026, -0.99778474, -1.01162495, -1.01955295]])

In [25]:
text_clf_svm.decision_function(["능동적인 사람이 되자"])

array([[-1.0146275 , -0.95802504, -0.99871353, -0.98876425, -1.00517826,
        -0.9965136 , -0.99421377, -0.96241667, -0.99252982, -1.00886482]])

In [27]:
text_clf_svm.predict(["능동적인 사람이 되자"])

array([2], dtype=int64)

In [34]:
keyword_names

['글로벌역량', '능동', '도전', '성실', '소통', '인내심', '정직', '주인의식', '창의', '팀워크']

In [35]:
def SVMpredict(text):
    result = text_clf_svm.predict([text])
    return keyword_names[result[0]-1]

In [49]:
SVMpredict("개정안에 따르면, 앞으로 산업기술 R&D는 ‘신속한 기술개발’을 우선 고려한다. 이를 위해 연구수행자는 ‘기존 기술의 도입을 통한 기간 단축 및 사업비 절감방안’을 사업계획서에 반드시 포함하도록 했고, 신규평가에서도 이 내용을 검토할 예정이다. 이를 통해 산업기술 R&D 전반의 개발 속도가 단축돼 4차 산업혁명 시대에 급변하는 외부환경 변화에 적기대응할 수 있는 제도적 기반을 갖추게 될 전망이다.")

'능동'

In [50]:
SVMpredict("또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다. ")

'팀워크'

In [51]:
import pickle
from sklearn.externals import joblib

In [52]:
saved_model = pickle.dumps(text_clf_svm)

In [53]:
joblib.dump(text_clf_svm, 'SVMmodel.pkl') 

['SVMmodel.pkl']

In [54]:
clf_from_joblib = joblib.load('SVMmodel.pkl') 
clf_from_joblib.predict(["또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다."])

array([10], dtype=int64)

In [55]:
filename = 'SVMmodel.pkl'
clf_from_pickle = joblib.load(filename)

In [56]:
clf_from_pickle.predict(["또한, 산업의 난제를 푸는 ‘도전적 프로젝트(알키미스트 프로젝트)’의 시행을 위해 기획부터 평가방식까지 사업추진 방식을 전면 개선했다. 알키미스트 프로젝트는 6월부터 시범사업(국비 100억원 규모)을 추진하고, 2020년부터는 과기부와 협업과제를 발굴하여 본격 시행될 예정으롤 예비타당성 조사를 추진하고 있다."])

array([10], dtype=int64)

In [57]:
clf_from_pickle.predict(["오늘도 캡스톤을 하러 학교에 남았다"])

array([1], dtype=int64)

##### cloud에서 만든 model 테스트

In [60]:
filename = 'SVMmodel_cloud.pkl'
clf_from_pickle = joblib.load(filename)

In [61]:
cloud_predicted_svm = clf_from_pickle.predict(test["sentence"].apply(lambda x: np.str_(x)))#테스트데이터
np.mean(cloud_predicted_svm == test["label"])

0.9135794840105051