In [1]:
import os
import pandas as pd

ability_1 = pd.read_csv("data_in/challenge.csv", encoding="utf-8")
ability_2 = pd.read_csv("data_in/communication.csv", encoding="utf-8")
ability_3 = pd.read_csv("data_in/creativity.csv", encoding="utf-8")

ability_1.head()

sentence  ability
0                        도전하고 모험하는 건 제가 원래 그런 걸 좋아한다        0
1  백광 권영찬 교수가 최근 한 대기업 강연에서 실패는 성공의 바로 전 단계 도전을 즐...        0
2  3라운드 진출팀은 비록 없었으나 한국판 칼레의 기적을 꿈꾸는 사람들의 도전은 이어질...        0
3  의원회관2소회의실에서 열린 31절 100주년기념 대한민국 희망 프로젝트8th 도전한...        0
4  지난 인도양 편에서 넘치는 자부심으로 낚시에 도전했지만 0마리의 굴욕을 맛봤던 돈스...        0

In [2]:
ability_2.head()

sentence  ability
0  소통은 막히지 아니하고 잘 통함 또는 뜻이 서로 통하여 오해가 없음을 뜻합니다. 요...        1
1  위원 30명이 참석한 가운데 열린 이날 행사는 위촉장 수여 공동 결의문 낭독 소통의...        1
2  이번 간담회를 통해 주민과의 소통 강화는 물론 지역구가 다른 의원 간 소통 강화에도...        1
3  소통간담회는 민선7기 군정의 성공적인 추진과 본청 및 13개 읍면의대해서는 분기별로...        1
4                      이를 통해 고객과의 소통을 강화해 나가겠다는 전략이다        1

In [3]:
ability_3.head()

sentence  ability
0                    하지만 방법을 몰라 상상력 창의력 키우기에 그치고 있다         1
1   초등 창의융합체험 프로그램 모나르떼는 4차 산업혁명 시대를 맞아 분석력과 창의력을 바탕        1
2  이번 간담회를 통해 주민과의 소통 강화는 물론 지역구가 다른 의원 간 소통 강화에도...        1
3  사례 GED시스템을 활용한 관찰추천 방법 융합영재교육 프로그램 재구성의 실제 창의적...        1
4  프린팅 기술창업 육성과정 3D프린팅 창의교실 △찾아가는 4차산업 미래기술 등으로, ...        1

In [4]:
a1 = pd.DataFrame(ability_1["sentence"])
a1["label"] = 1
a1.head()

sentence  label
0                        도전하고 모험하는 건 제가 원래 그런 걸 좋아한다      1
1  백광 권영찬 교수가 최근 한 대기업 강연에서 실패는 성공의 바로 전 단계 도전을 즐...      1
2  3라운드 진출팀은 비록 없었으나 한국판 칼레의 기적을 꿈꾸는 사람들의 도전은 이어질...      1
3  의원회관2소회의실에서 열린 31절 100주년기념 대한민국 희망 프로젝트8th 도전한...      1
4  지난 인도양 편에서 넘치는 자부심으로 낚시에 도전했지만 0마리의 굴욕을 맛봤던 돈스...      1

In [5]:
a2 = pd.DataFrame(ability_2["sentence"])
a2["label"] = 2
a2.head()

sentence  label
0  소통은 막히지 아니하고 잘 통함 또는 뜻이 서로 통하여 오해가 없음을 뜻합니다. 요...      2
1  위원 30명이 참석한 가운데 열린 이날 행사는 위촉장 수여 공동 결의문 낭독 소통의...      2
2  이번 간담회를 통해 주민과의 소통 강화는 물론 지역구가 다른 의원 간 소통 강화에도...      2
3  소통간담회는 민선7기 군정의 성공적인 추진과 본청 및 13개 읍면의대해서는 분기별로...      2
4                      이를 통해 고객과의 소통을 강화해 나가겠다는 전략이다      2

In [6]:
a3 = pd.DataFrame(ability_3["sentence"])
a3["label"] = 3
a3.head()

sentence  label
0                    하지만 방법을 몰라 상상력 창의력 키우기에 그치고 있다       3
1   초등 창의융합체험 프로그램 모나르떼는 4차 산업혁명 시대를 맞아 분석력과 창의력을 바탕      3
2  이번 간담회를 통해 주민과의 소통 강화는 물론 지역구가 다른 의원 간 소통 강화에도...      3
3  사례 GED시스템을 활용한 관찰추천 방법 융합영재교육 프로그램 재구성의 실제 창의적...      3
4  프린팅 기술창업 육성과정 3D프린팅 창의교실 △찾아가는 4차산업 미래기술 등으로, ...      3

In [7]:
data = a1.append(a2)
data = data.append(a3)


In [8]:
data.shape
print(data)

                                            sentence  label
0                        도전하고 모험하는 건 제가 원래 그런 걸 좋아한다      1
1  백광 권영찬 교수가 최근 한 대기업 강연에서 실패는 성공의 바로 전 단계 도전을 즐...      1
2  3라운드 진출팀은 비록 없었으나 한국판 칼레의 기적을 꿈꾸는 사람들의 도전은 이어질...      1
3  의원회관2소회의실에서 열린 31절 100주년기념 대한민국 희망 프로젝트8th 도전한...      1
4  지난 인도양 편에서 넘치는 자부심으로 낚시에 도전했지만 0마리의 굴욕을 맛봤던 돈스...      1
5       미세먼지를 없앨 수 있는 기술에 도전하는 과학기술자가 늘어날 수밖에 없는 구조다      1
6  2007년부터 미국프로골프협회투어에 도전하는 등 빅 리그 진출을 끊임없이 꿈꿨던 그...      1
7  과거 전설적인 예능 프로그램 근간이라고 생각하는 무한도전과 1박2일처럼 꾸려졌던 멤...      1
0  소통은 막히지 아니하고 잘 통함 또는 뜻이 서로 통하여 오해가 없음을 뜻합니다. 요...      2
1  위원 30명이 참석한 가운데 열린 이날 행사는 위촉장 수여 공동 결의문 낭독 소통의...      2
2  이번 간담회를 통해 주민과의 소통 강화는 물론 지역구가 다른 의원 간 소통 강화에도...      2
3  소통간담회는 민선7기 군정의 성공적인 추진과 본청 및 13개 읍면의대해서는 분기별로...      2
4                      이를 통해 고객과의 소통을 강화해 나가겠다는 전략이다      2
5  스타벅스는 새로운 콘텐츠인 스벅TV를 통해 고객과의 소통을 강화해 나갈 예정이다고 ...      2
6  15일 두나무는 회사와 서비스 관련한 정확한 정보 제공 및 신뢰 기반의 고객 소통을...      2
7   무역협회 경영진이 경기도를 시작으로 전국 수출현장의 목소리를 듣기

In [9]:
print(data["label"])

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
0    2
1    2
2    2
3    2
4    2
5    2
6    2
7    2
0    3
1    3
2    3
3    3
4    3
5    3
6    3
7    3
Name: label, dtype: int64


In [10]:
import numpy as np
from sklearn.model_selection import train_test_split

In [11]:
train, test = train_test_split(data, test_size=0.33, random_state=42)

In [12]:
train["label"] = pd.Categorical(train["label"])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [13]:
train.groupby("label").count()

sentence
label          
1             6
2             4
3             6

In [14]:
test.groupby("label").count()

sentence
label          
1             2
2             4
3             2

In [15]:
from konlpy.tag import Twitter
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
def get_noun(text):
    tokenizer = Twitter()
    nouns = tokenizer.nouns(text)
    return [n for n in nouns]

In [17]:
cv = CountVectorizer(tokenizer=get_noun,stop_words=None, ngram_range=(1, 2))

In [18]:
tdm = cv.fit_transform(train["sentence"])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/konlpy/tag/_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline

text_clf_svm = Pipeline([('vect', CountVectorizer(tokenizer=get_noun)),
                         ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2', alpha=1e-3, n_iter=5, random_state=42))])

text_clf_svm = text_clf_svm.fit(train["sentence"], train["label"])


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


In [20]:
print(cv.vocabulary_)

{'문재인': 129, '대통령': 76, '세대': 189, '이': 260, '해': 378, '것': 11, '해체': 380, '융합': 249, '창의': 312, '사고': 161, '차': 305, '산업혁명': 175, '시대': 206, '필요': 370, '인재': 269, '말': 112, '문재인 대통령': 130, '대통령 세대': 77, '세대 이': 190, '이 해': 261, '해 것': 379, '것 해체': 12, '해체 융합': 381, '융합 창의': 251, '창의 사고': 314, '사고 차': 162, '차 산업혁명': 307, '산업혁명 시대': 176, '시대 필요': 208, '필요 인재': 371, '인재 말': 270, '미세먼지': 137, '수': 198, '기술': 54, '도전': 85, '과학기술': 27, '구조': 39, '미세먼지 수': 138, '수 기술': 200, '기술 도전': 55, '도전 과학기술': 87, '과학기술 수': 28, '수 구조': 199, '라운드': 104, '진출': 302, '팀': 349, '비록': 157, '한국판': 376, '칼레': 336, '기적': 60, '사람': 163, '라운드 진출': 105, '진출 팀': 304, '팀 비록': 350, '비록 한국판': 158, '한국판 칼레': 377, '칼레 기적': 337, '기적 사람': 61, '사람 도전': 164, '도전 것': 86, '통해': 342, '고객': 17, '소통': 193, '전략': 275, '통해 고객': 343, '고객 소통': 18, '소통 전략': 196, '무역': 125, '협회': 389, '영진': 229, '경기도': 13, '시작': 213, '전국': 273, '출현': 332, '목소리': 121, '듣기': 96, '위': 236, '행보': 382, '무역 협회': 126, '협회 영진': 390, '영진 경기도': 230, '경기도 시작': 14,

In [21]:
predicted_svm = text_clf_svm.predict(test["sentence"])
np.mean(predicted_svm == test["label"])

0.75

In [22]:

text_clf_svm.predict(["도전"]) # 결과 예측
print (text_clf_svm.decision_function(["도전"])) # 예측 수치 값

[[ 4.17925566 -3.70091679 -4.48716577]]


In [23]:
 text_clf_svm.predict(["의사 소통"])

array([2])

In [24]:
 text_clf_svm.predict(["산업혁명"])

array([3])